export const SHARE_LOCATION = 'SHARE_LOCATION'
export const GET_CUSTOMER_ORDER_LOCATION = 'GET_CUSTOMER_ORDER_LOCATION'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'