export const SHARE_LOCATION = 'SHARE_LOCATION'
export const GET_CUSTOMER_ORDER_LOCATION = 'GET_CUSTOMER_ORDER_LOCATION'

export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'

//AUTH
export const TRY_AUTH = 'TRY_AUTH'
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN'

//USER
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

//CUSTOMER
export const GET_CUSTOMER = 'GET_CUSTOMER'
export const UPDATE_CUSTOMRT = 'UPDATE_CUSTOMER'

export const SET_CUSTOMERS = 'SET_CUSTOMERS'
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const CUSTOMER_ADDED = 'CUSTOMER_ADDED'
export const START_ADD_CUSTOMER = 'START_ADD_CUSTOMER'
export const SEARCH_CUSTOMER = 'SEARCH_CUSTOMER'
export const STOP_SEARCH_CUSTOMER = 'STOP_SEARCH_CUSTOMER'
export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER'
export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER'
export const SELECT_CUSTOMERS = 'SELECT_CUSTOMERS'
export const CLEAR_SELECT_CUSTOMERS = 'CLEAR_SELECT_CUSTOMERS'
