export {shareLocation, getCustomerOrders, getCustomerLastSavedLocation} from './location'
export { login,authAutoSignIn,authClearStorage,authGetToken,authLogout,authRemoveToken,authSetToken,authStoreToken } from './auth'
export { uiStartLoading, uiStopLoading } from './ui'
export { signup, getLoggedCustomer,customerLogIn, updateLoggedCustomer, updateAvatar } from './customers'
export { vendorSignup, getLoggedVendor, updateLoggedVendor, searchVendor, getAllVendors } from './vendor'
export {setCart, clearCart, createOrder} from './order'